spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mybatis?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

mybatis:
  type-aliases-package: com.example.mybatis.dto
  mapper-locations: mapper/**/*.xml

pagehelper:
  helper-dialect: mariadb
  reasonable: true # 범위를 넘어가는 pageNum 일 경우 가능한 값으로 바꿔준다.
